import React from 'react'
import { Link } from 'react-router-dom'

export default function Signup() {
    return (
        <>
            <section>
                <div className="sign py-5">
                    <div className="container">
                        <h1> Create Your Account</h1>
                    </div>
                </div>
                <div className="container py-4">
                    <div className="row">
                        <div className="col-lg-6 d-lg-block d-none">
                            <div className=" mb-4" style={{}}>
                                <div className="row g-0">
                                    <div className="col-lg-3 py-4 ps-5 ">
                                        <img src="https://www.splunk.com/content/dam/splunk2/images/2020-splunk-planet.svg" className="img-fluid rounded-start" alt="..." style={{ height: '70px' }} />
                                    </div>
                                    <div className="col-lg-9 ">
                                        <div className="card-body py-3">

                                            <p className="card-text">Operational Intelligence gives you a real-time understanding of what's happening across your IT systems and technology infrastructure so you can make informed decisions. It is enabled by the Splunk platform, the foundation for all of Splunk's products, premium solutions, apps and add-ons.</p>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* card-2 */}
                            <div className=" mb-4" style={{}}>
                                <div className="row g-0">
                                    <div className="col-lg-3  py-4 ps-5 ">
                                        <img src="https://www.splunk.com/content/dam/splunk2/images/icon-library/standard/cloud-download.svg" className="img-fluid rounded-start" alt="..." style={{ height: '70px' }} />
                                    </div>
                                    <div className="col-lg-9">
                                        <div className="card-body py-3">
                                            <h5 class="card-title fw-bold fs-5 pb-4">Free Trials and Downloads</h5>
                                            <p className="card-text">Search, analyze and visualize the massive streams of machine data generated by your IT systems and technology infrastructure-physical, virtual and in the cloud.</p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            {/* card-3 */}

                            <div className=" mb-4" style={{}}>
                                <div className="row g-0">
                                    <div className="col-lg-3  py-4 ps-5 ">
                                        <img src="https://www.splunk.com/content/dam/splunk2/images/icon-library/standard/splunkbase-apps-and-add-ons.svg" className="img-fluid rounded-start" alt="..." style={{ height: '70px' }} />
                                    </div>
                                    <div className="col-lg-9">
                                        <div className="card-body py-3">
                                            <h5 class="card-title fw-bold fs-5 pb-4">Splunkbase Apps and Add-Ons</h5>
                                            <p className="card-text">Search, analyze and visualize the massive streams of machine data generated by your IT systems and technology infrastructure-physical, virtual and in the cloud.</p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            {/* card-4 */}
                            <div className=" mb-4" style={{}}>
                                <div className="row g-0">
                                    <div className="col-lg-3  py-4 ps-5 ">
                                        <img src="https://www.splunk.com/content/dam/splunk2/images/icon-library/standard/user.svg" className="img-fluid rounded-start" alt="..." style={{ height: '70px' }} />
                                    </div>
                                    <div className="col-lg-9">
                                        <div className="card-body py-3">
                                            <h5 class="card-title fw-bold fs-5 pb-4">
                                                Help When You Need It</h5>
                                            <p className="card-text">Search, analyze and visualize the massive streams of machine data generated by your IT systems and technology infrastructure-physical, virtual and in the cloud.</p>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* card-5 */}
                            <div className=" mb-4" style={{}}>
                                <div className="row g-0">
                                    <div className="col-lg-3  py-4 ps-5 ">
                                        <img src="https://www.splunk.com/content/dam/splunk2/images/icon-library/standard/global-business.svg" className="img-fluid rounded-start" alt="..." style={{ height: '70px' }} />
                                    </div>
                                    <div className="col-lg-9">
                                        <div className="card-body py-3">
                                            <h5 class="card-title fw-bold fs-5 pb-4">Community</h5>
                                            <p className="card-text">Search, analyze and visualize the massive streams of machine data generated by your IT systems and technology infrastructure-physical, virtual and in the cloud.</p>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div className="col-lg-5">
                            <div className="form-1 mx-5 px-4 py-4">
                                <h5 className='fw-bold pb-4'>Create Your Splunk Account</h5>
                                <div className='d-flex  ' >
                                    <p style={{ fontSize: '14px' }} >Already have a Splunk account? <Link to="/login" style={{ color: '#E8339B' }} className='text-decoration-none'>Log in</Link></p>

                                </div>
                                <form action="">
                                    <input type="email" className="form-control py-3 my-3" placeholder="Business Email" aria-label="" />
                                    <input type="password" className="form-control  py-3 my-3" id="inputPassword4" placeholder='Password' />

                                    <input type="text" className="form-control py-3 my-3" placeholder="First Name" aria-label="" />
                                    <input type="text" className="form-control py-3 my-3" placeholder="Last Name" aria-label="" />
                                    <input type="text" className="form-control py-3 my-3" placeholder="Job Title" aria-label="" />
                                    <input type="text" className="form-control py-3 my-3" placeholder="Phone Number" aria-label="" />
                                    <input type="text" className="form-control py-3 my-3" placeholder="Company" aria-label="" />
                                    <select id="inputState" className="form-select py-3 my-3">
                                        <option selected>Nepal</option>
                                        <option>America</option>
                                        <option>India</option>
                                        <option>China</option>
                                        <option>Japan</option>
                                        <option>Crotia</option>
                                        <option>Uganda</option>
                                    </select>
                                    <input type="text" className="form-control py-3 my-3" placeholder="Zip/Postal Code" aria-label="" />

                                    <div className="form-check">
                                        <input className="form-check-input" type="checkbox" id="gridCheck" />
                                        <label className="form-check-label" htmlFor="gridCheck">
                                           I agree to the terms & conditions of Use, splunk Privacy
                                           & Policy.
                                        </label>
                                    </div>
                                    <div class="col-lg-12 d-flex justify-content-center ">

                                    <button type="button" class="btn ">Create Account</button>

                                    </div>


                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
